// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pairwise_chisq_cpp
List pairwise_chisq_cpp(NumericMatrix mat, IntegerVector resp, double min_prop, double max_prop, double chisq_cutoff, double diff_cutoff, double min_valid_prop);
RcppExport SEXP _immunePairMarker_pairwise_chisq_cpp(SEXP matSEXP, SEXP respSEXP, SEXP min_propSEXP, SEXP max_propSEXP, SEXP chisq_cutoffSEXP, SEXP diff_cutoffSEXP, SEXP min_valid_propSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type resp(respSEXP);
    Rcpp::traits::input_parameter< double >::type min_prop(min_propSEXP);
    Rcpp::traits::input_parameter< double >::type max_prop(max_propSEXP);
    Rcpp::traits::input_parameter< double >::type chisq_cutoff(chisq_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type diff_cutoff(diff_cutoffSEXP);
    Rcpp::traits::input_parameter< double >::type min_valid_prop(min_valid_propSEXP);
    rcpp_result_gen = Rcpp::wrap(pairwise_chisq_cpp(mat, resp, min_prop, max_prop, chisq_cutoff, diff_cutoff, min_valid_prop));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_immunePairMarker_pairwise_chisq_cpp", (DL_FUNC) &_immunePairMarker_pairwise_chisq_cpp, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_immunePairMarker(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
