# Generated by Rcpp::compileAttributes(); manual copy for initial package scaffold.

pairwise_chisq_cpp <- function(mat, resp, min_prop = 0.05, max_prop = 0.95,
                               chisq_cutoff = 0.01, diff_cutoff = 0.0,
                               min_valid_prop = 0.5) {
  .Call(
    "_immunePairMarker_pairwise_chisq_cpp",
    mat,
    resp,
    min_prop,
    max_prop,
    chisq_cutoff,
    diff_cutoff,
    min_valid_prop,
    PACKAGE = "immunePairMarker"
  )
}
